// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3f5cf2QeR3NxPOU9Dg_FMCGj8vMXubtA',
    appId: '1:541024069294:web:ab0609a6347731dbaeef3f',
    messagingSenderId: '541024069294',
    projectId: 'dlights-flutter-myapp',
    authDomain: 'dlights-flutter-myapp.firebaseapp.com',
    storageBucket: 'dlights-flutter-myapp.appspot.com',
    measurementId: 'G-PQZVDSQ1FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOhr3v4xUZ59FG4lhF4XKVrs-6uDVh9OM',
    appId: '1:541024069294:android:becf255fd776a46faeef3f',
    messagingSenderId: '541024069294',
    projectId: 'dlights-flutter-myapp',
    storageBucket: 'dlights-flutter-myapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB3zq0Yb6WPfqHdsukGmWXciw1rfwhCoE',
    appId: '1:541024069294:ios:f7b5b92d58ca3711aeef3f',
    messagingSenderId: '541024069294',
    projectId: 'dlights-flutter-myapp',
    storageBucket: 'dlights-flutter-myapp.appspot.com',
    iosClientId: '541024069294-h192j8fsbf8ibl3pcaa083pa6o2b4gvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB3zq0Yb6WPfqHdsukGmWXciw1rfwhCoE',
    appId: '1:541024069294:ios:f7b5b92d58ca3711aeef3f',
    messagingSenderId: '541024069294',
    projectId: 'dlights-flutter-myapp',
    storageBucket: 'dlights-flutter-myapp.appspot.com',
    iosClientId: '541024069294-h192j8fsbf8ibl3pcaa083pa6o2b4gvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
